<!-- formulario de alta de tarea -->

<div class="containerFormEditCategoria">
<form class="formEditarCategoria" action="enviarFormEditCategory" method="POST" class="my-4">
<div class="containerTitleSingIng">
            <h1 class="h1Editar">Editar: "<?php echo $categoria ?>"</h1>
        </div>
            <div class="form-group inputFormEditar">
            <input type="number" hidden name="id_categoria" value="<?php echo $id_categoria ?>">
                <label>Nuevo nombre:</label>
                <input required name="nombre_categoria" type="text" class="form-control">
            </div>
        

    <button type="submit" class="btn btn-primary mt-2">Editar</button>
</form>
</div>
