<div class="container containerCardItem">
        <div class="row rp">
                <div class="col-md-12 bg-primary d-flex justify-content-center p-3">
                        
                        <a href="modificarProducto/<?php echo $id_producto;?>">
                                <button tyrpe="button" class="btn btn-dark me-md-2">Editar</button>
                        </a>

                        <a href="eliminarProducto/<?php echo $id_producto;?>">
                                <button type="button" class="btn btn-danger">Eliminar</button>
                        </a>
                </div>
        
        </div>

</div>