<!DOCTYPE html>
<html>
<head>
    <title>Agregar Productos</title>
</head>
<body>
    <h1>Agregar Productos</h1>
    <form action="procesar" method="post">
        <label for="nombre">Nombre del Producto:</label>
        <input type="text" id="nombre" name="nombre" required><br>

        <label for="precio">Precio:</label>
        <input type="number" id="precio" name="precio" required><br>

        <label for="categoria">Categoría:</label>
        <select id="categoria" name="categoria">
            <option value="Audio y video">Audio</option>
            <option value="Aire y Climatizacion">Aire</option>
            <option value="Heladeras">Heladera</option>
            <option value="Lavarropas">Lavarropas</option>
        </select><br>

        <input type="submit" value="Agregar Producto">
    </form>
</body>
</html>
