<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Dancing+Script&family=Gabarito&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="css/style.css">
    <title>TecnoTandil</title>
</head>

<body>

    <header>
        <div class="containerH1Title">
            <h1 class="h1Title"><a class="navbar-brand" href="index">TecnoTandil</a></h1>
        </div>
        <nav class="navbar navbar-expand-lg bg-light containerNav">

            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                            <a class="itemNav" class="nav-link" aria-current="page" href="productos">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="itemNav" class="nav-link" aria-current="page" href="categorias">Categorias</a>
                        </li>
                        <?php if ((!isset($_SESSION["id_user"]))) : ?>

                        <li class="nav-item" id="btnRegister">
                            <a class="itemNav" class="nav-link" aria-current="page"  href="register">Registrarse</a>
                        </li>
                           
                        <?php endif ?>
                        <?php if (!isset($_SESSION['email'])) : ?>
                        <li  class="nav-item" id="btnSingIn">
                            <a class="itemNav" class="nav-link" aria-current="page" href="login">Iniciar sesion</a>
                        </li>
                        <?php else : ?>
                        <li class="nav-item btnLogout">
                            <a id="btnLogOut" class="itemNav" class="nav-link" aria-current="page" href="logout">Cerrar Sesion <span>(<?= $_SESSION['email'] ?>)</span></a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <!-- inicio main container -->


</body>
</html>