<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <h1>Sing in</h1>
        <div class="form-group">
            <input type="email" required class="form-control" id="email" name="email" placeholder="email" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <input type="password" required class="form-control" id="password" name="password"placeholder="password" >
        </div>
        <div class="form-group">
            <input type="text" hidden class="form-control" id="rol" name="rol" value="admin">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>
