    <?php require_once './templates/header.phtml';?>
    <h2>Register</h2>
    <form class="row g-3" method="POST" action="verifyRegister">
        <div class="col-auto">
            <label for="staticEmail2" class="visually-hidden">Email</label>
            <input type="email" name="email" class="form-control-plaintext" id="staticEmail2" placeholder="email">
        </div>
        <div class="col-auto">
            <label for="inputPassword2" class="visually-hidden">Password</label>
            <input name="password" type="password" class="form-control" id="inputPassword2" placeholder="Password">
        </div>
        <div class="col-auto">
            <input name="rol" type="text" value="usuario" class="form-control" id="rol" placeholder="rol" >
        </div>
        <div class="col-auto">
            <button>Register</button>
        </div>
    </form>
