<?php require_once './templates/header.phtml';?>
        
<div class="row">
          <?php foreach($productos as $t){?>
            <div class="col-sm-6">
                <div class="card text-center" style="width: 18rem">
                    <div class="card-body">
                        <a href="verProducto/<?php echo $t->id_producto?>"> <?php echo $t->nombre_producto?></a>
                    </div>
                </div>
            </div>        <?php } ?>

<?php if (isset($_SESSION['email'])) : ?>
    <?php require_once './templates/formProducto.phtml'; ?>
<?php endif; ?>

<?php
