<?php
        class viewCategorias{
            

    public function viewCategoryWithProducts($categ){
        require_once './templates/showItem.phtml';
    }
        public function viewCategoryRolUser(){
            require_once './templates/showCategoryRolUser.phtml';
        }


////////////////////

public function showCategorys($categorias){
    require_once './templates/showCategory.phtml';


}


public function viewCategoryUser($categ){
    require_once './templates/showCategoryRolUser.phtml';
}
////////////////////

        function viewItem($categ){
            require_once './templates/header.phtml';
            require_once './templates/showItem.phtml';
            ?>
            <?php
        }
        function viewCategoryButton($catego){
            require_once './templates/header.phtml';
            require_once './app/templates/category.phtml';
            require_once './app/templates/categoryButton.phtml';
            ?>
                <?php
        }
        
        
        function mostrarForm(){
            require_once './templates/header.phtml';
        require_once './templates/formCategory.phtml';
        }
        public function mostrarFormEditCategory($id_categoria){
            require_once './templates/header.phtml';
            require_once './templates/formEditarCategory.phtml';
            ?>
<?php
        }
        public function mostrarError($error){
            require 'templates/header.phtml';
            require 'templates/showError.phtml';
            require 'templates/footer.phtml';
        }
    }